### PR TITLE
Adding a maximum length validtion for strings

### PR DESCRIPTION
**Pull request by edgibbs**
Just adding a maximum length validation for strings.

### CODE REVIEW

**Comment by leonardoborges** [comment]
Any reason this validator applies to strings only?

**Comment by edgibbs** [comment]
I didn't have any use cases for testing the length of anything other than strings.

**Comment by leonardoborges** [comment]
Fair enough. The implementation could easily be updated to work with any sequences however. That would make it more reusable - if you need it to be a string you could combine both v/string (merged recently) and your v/max-length.

Additionally, I'd rename max-length to count.

What do you think? If you update the PR, I'm happy to merge it. You might need to pull as other PR's have been merged since you first submitted this one.

Thanks

**Comment by edgibbs** [comment]
Sounds good, I'll take a look at it tomorrow.

**Comment by leonardoborges** [comment]
Awesome. Thanks.

**Comment by Skinney** [comment]
I was wondering, if it wasn't to much trouble, could you create a min-length validator as well?

**Comment by edgibbs** [comment]
OK, I'll add the min as well, but any preference on the names:

* count, min-count
* max-count, min-count
* max-length, min-length

**Comment by Skinney** [comment]
My preference is min-length and max-length

**Comment by leonardoborges** [comment]
My preference is `max-count` and `min-count`.

My reasoning for this is that Clojure already has a `count` function which works on sequences, therefore they seem more intuitive.

**Comment by Skinney** [comment]
I don't have a strong preference, and leonardoborges makes a fair point.

**Comment by Skinney** [comment]
Changes look good to me :+1:

**Pull request merged**
